resource: kubernetes-1.15.4
version: 1.15.4
components:
  kubernetes: 1.15.4
  etcd: 3.3.10
  docker: docker-ce-18.09.9
images:
  - name: quay.io/external_storage/nfs-client-provisioner
    tag: v3.1.0-k8s1.11
  - name: docker.io/traefik
    tag: v1.7.11
  - name: docker.io/grafana/grafana
    tag: 5.2.1
  - name: quay.io/prometheus/alertmanager
    tag: v0.15.2
  - name: docker.io/busybox
    tag: 1.31.0
  - name: quay.io/prometheus/node-exporter
    tag: v0.15.2
  - name: quay.io/prometheus/prometheus
    tag: v2.4.3
  - name: quay.io/prometheus/pushgateway
    tag: v0.5.2
  - name: docker.io/coredns/coredns
    tag: 1.6.0
  - name: quay.io/coreos/flannel
    tag: v0.11.0-amd64
  - name: gcr.io/kubernetes-helm/tiller
    tag: v2.12.3
  - name: kubernetesui/dashboard
    tag: v2.0.0-beta4
  - name: kubernetesui/metrics-scraper
    tag: v1.0.1
  - name: quay.io/coreos/configmap-reload
    tag: v0.0.1
  - name: gcr.io/google-containers/pause-amd64
    tag: 3.1
  - name: docker.io/registry
    tag: 2
  - name: docker.io/alpine
    tag: 3.6
  - name: quay.io/coreos/kube-state-metrics
    tag: v1.4.0
  - name: appropriate/curl
    tag: edge
  - name: docker.io/konradkleine/docker-registry-frontend
    tag: v2
  - name: docker.io/weaveworks/scope
    tag: 1.11.5
  - name: calico/node
    tag: v3.7.3
  - name: calico/cni
    tag: v3.7.3
  - name: calico/kube-controllers
    tag: v3.7.3
  - name: cluster-proportional-autoscaler-amd64
    tag: 1.6.0
vars:
  bin_dir: "/usr/local/bin"
  ca_dir: "/etc/kubernetes/ssl"
  CONTAINER_RUNTIME: "docker"
  base_dir: "/opt/kubeOperator-kube-bin/1.15.4"
  kube_version: "1.15.4"
  docker_version: "18.09.9"
  etcd_version: "3.3.10"

  repo_port: 8083
  registry_port: 8093
  registry_prefix: "registry.kubeops.io"
  download_path: "repository/raw/1.15.4/k8s.1-15-4.tar.gz"
  file_name: "k8s.1-15-4.tar.gz"

  #kubelet
  SANDBOX_IMAGE_NAME: "gcr.io/google-containers/pause-amd64"
  SANDBOX_VERSION: "3.11"
  #dns
  dns_install: true
  dns_image: "docker.io/coredns/coredns"
  dns_version: "1.6.0"
  cluster-proportional-autoscaler-amd64_image: gcr.io/google-containers/cluster-proportional-autoscaler-amd64

  #dashboard
  dashboard_install: true
  dashboard_image: "kubernetesui/dashboard"
  dashboard_version: "v2.0.0-beta4"
  metrics-scraper_image: kubernetesui/metrics-scraper
  metrics-scraper_version: v1.0.1

  #traefik
  traefik_version: "v1.7.11"
  traefik_image: "docker.io/traefik"


  #helm
  helm_namespace: kube-system
  helm_cert_cn: helm001
  tiller_sa: tiller
  tiller_cert_cn: tiller001
  tiller_image: "gcr.io/kubernetes-helm/tiller"
  tiller_version: "v2.12.3"

  #flannel
  NODE_WITH_MULTIPLE_NETWORKS: "true"
  flanneld_image: "quay.io/coreos/flannel"
  flanneld_version: "v0.11.0-amd64"


  #calico
  calico_ver: "v3.7.3"

  #registry
  REGISTRY_ACCOUNT_NAME: admin
  REGISTRY_ACCOUNT_PASSWORD: admin123
  IMAGE_PULL_SECRET: registry-fit2cloud-com-key

  #kuberhealthy
  kuberhealthy_image: quay.io/comcast/kuberhealthy
  kuberhealthy_version: v1.0.2
  kuberhealthy_pause: gcr.io/google_containers/pause
  kuberhealthy_pause_version: 0.8.0

  #prometheus


  alertmanager_image: quay.io/prometheus/alertmanager
  alertmanager_version: v0.15.2
  busybox_image: docker.io/busybox
  busybox_version: 1.31.0
  node-exporter_image: quay.io/prometheus/node-exporter
  node-exporter_version: v0.15.2
  prometheus_image: quay.io/prometheus/prometheus
  prometheus_version: v2.4.3
  pushgateway_image: quay.io/prometheus/pushgateway
  pushgateway_version: v0.5.2
  kube-state-metrics_image: quay.io/coreos/kube-state-metrics
  kube-state-metrics_version: v1.4.0
  configmap-reload_image: quay.io/coreos/configmap-reload
  configmap-reload_version: v0.0.1

  #grafana
  grafana_image: docker.io/grafana/grafana
  grafana_version: 5.2.1
  curl_image: appropriate/curl
  curl_version: edge

  #scope
  scope_image: docker.io/weaveworks/scope
  scope_version: 1.11.5
