resource: kubernetes-1.16.2
version: 1.16.2
components:
  kubernetes: 1.16.2
  etcd: 3.3.10
  docker: docker-ce-18.09.9
images:
  - name: quay.io/external_storage/nfs-client-provisioner
    tag: v3.1.0-k8s1.11
  - name: docker.io/traefik
    tag: v1.7.11
  - name: docker.io/grafana/grafana
    tag: 6.4.3
  - name: quay.io/prometheus/alertmanager
    tag: v0.15.2
  - name: docker.io/busybox
    tag: 1.31.0
  - name: quay.io/prometheus/node-exporter
    tag: v0.18.0
  - name: quay.io/prometheus/prometheus
    tag: v2.4.3
  - name: quay.io/prometheus/pushgateway
    tag: v0.5.2
  - name: docker.io/coredns/coredns
    tag: 1.6.0
  - name: quay.io/coreos/flannel
    tag: v0.11.0-amd64
  - name: gcr.io/kubernetes-helm/tiller
    tag: v2.15.0
  - name: kubernetesui/dashboard
    tag: v2.0.0-beta5
  - name: kubernetesui/metrics-scraper
    tag: v1.0.1
  - name: k8s.gcr.io/metrics-server-amd64
    tag: v0.3.6
  - name: quay.io/coreos/configmap-reload
    tag: v0.0.1
  - name: gcr.io/google-containers/pause-amd64
    tag: 3.1
  - name: docker.io/registry
    tag: 2
  - name: docker.io/alpine
    tag: 3.6
  - name: quay.io/coreos/kube-state-metrics
    tag: v1.4.0
  - name: appropriate/curl
    tag: edge
  - name: docker.io/konradkleine/docker-registry-frontend
    tag: v2
  - name: weaveworks/scope
    tag: 1.11.5
  - name: calico/node
    tag: v3.7.3
  - name: calico/cni
    tag: v3.7.3
  - name: calico/kube-controllers
    tag: v3.7.3
  - name: grafana/loki
    tag: v0.4.0
  - name: grafana/promtail
    tag: v0.4.0
  - name: rook/ceph
    tag: v1.1.6
  - name: quay.io/cephcsi/cephcsi
    tag: v1.2.1
  - name: quay.io/k8scsi/csi-node-driver-registrar
    tag: v1.1.0
  - name: quay.io/k8scsi/csi-provisioner
    tag: v1.3.0
  - name: quay.io/k8scsi/csi-snapshotter
    tag: v1.2.0
  - name: quay.io/k8scsi/csi-attacher
    tag: v1.2.0
  - name: ceph/ceph
    tag: v14.2.4-20190917
vars:
  bin_dir: "/usr/local/bin"
  ca_dir: "/etc/kubernetes/ssl"
  CONTAINER_RUNTIME: "docker"
  base_dir: "/opt/kubeOperator-kube-bin/1.16.2"
  kube_version: "1.16.2"
  docker_version: "18.09.9"
  etcd_version: "3.3.10"
  repo_port: 8085
  registry_port: 8095
  registry_prefix: "registry.kubeops.io"
  download_path: "repository/raw/1.16.2/k8s.1-16-2.tar.gz"
  file_name: "k8s.1-16-2.tar.gz"

  #kubelet
  SANDBOX_IMAGE_NAME: "gcr.io/google-containers/pause-amd64"
  SANDBOX_VERSION: "3.1"
  
  #dns
  dns_install: true
  dns_image: "docker.io/coredns/coredns"
  dns_version: "1.6.0"

  #dashboard
  dashboard_install: true
  dashboard_image: "kubernetesui/dashboard"
  dashboard_version: "v2.0.0-beta5"
  metrics_scraper_image: kubernetesui/metrics-scraper
  metrics_scraper_version: v1.0.1

  #metrics_server
  metrics_server_amd64_image: k8s.gcr.io/metrics-server-amd64
  metrics_server_amd64_version: v0.3.6
  metrics_server_install: true

  #traefik
  traefik_version: "v1.7.11"
  traefik_image: "docker.io/traefik"
  
  #helm
  helm_namespace: kube-system
  helm_cert_cn: helm001
  tiller_sa: tiller
  tiller_cert_cn: tiller001
  tiller_image: "gcr.io/kubernetes-helm/tiller"
  tiller_version: "v2.15.0"

  #flannel
  NODE_WITH_MULTIPLE_NETWORKS: "true"
  flanneld_image: "quay.io/coreos/flannel"
  flanneld_version: "v0.11.0-amd64"

  #calico
  calico_ver: "v3.7.3"

  #registry
  REGISTRY_ACCOUNT_NAME: admin
  REGISTRY_ACCOUNT_PASSWORD: admin123
  IMAGE_PULL_SECRET: registry-fit2cloud-com-key

  #prometheus
  alertmanager_image: quay.io/prometheus/alertmanager
  alertmanager_version: v0.15.2
  busybox_image: docker.io/busybox
  busybox_version: 1.31.0
  node_exporter_image: quay.io/prometheus/node-exporter
  node_exporter_version: v0.18.0
  prometheus_image: quay.io/prometheus/prometheus
  prometheus_version: v2.4.3
  pushgateway_image: quay.io/prometheus/pushgateway
  pushgateway_version: v0.5.2
  kube_state_metrics_image: quay.io/coreos/kube-state-metrics
  kube_state_metrics_version: v1.4.0
  configmap_reload_image: quay.io/coreos/configmap-reload
  configmap_reload_version: v0.0.1

  #grafana
  grafana_image: docker.io/grafana/grafana
  grafana_version: 6.4.3
  curl_image: appropriate/curl
  curl_version: edge

  #scope
  scope_image: weaveworks/scope
  scope_version: 1.11.5

  #loki
  loki_image: grafana/loki
  loki_version: v0.4.0
  promtail_image: grafana/promtail
  promtail_version: v0.4.0
  loki_install: true

  #rook
  storage_rook_ceph_install: true
  rook_ceph_image: rook/ceph
  rook_ceph_version: v1.1.6
  cephcsi_image: quay.io/cephcsi/cephcsi
  cephcsi_version: v1.2.1
  csi_node_driver_registrar_image: quay.io/k8scsi/csi-node-driver-registrar
  csi_node_driver_registrar_version: v1.1.0
  csi_provisioner_image: quay.io/k8scsi/csi-provisioner
  csi_provisioner_version: v1.3.0
  csi_snapshotter_image: quay.io/k8scsi/csi-snapshotter
  csi_snapshotter_version: v1.2.0
  csi_attacher_image: quay.io/k8scsi/csi-attacher
  csi_attacher_version: v1.2.0
  ceph_ceph_image: ceph/ceph
  ceph_ceph_version: v14.2.4-20190917
